<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.comac</groupId>
        <artifactId>measure</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>measure-common-log</module>
        <module>measure-common-core</module>
        <module>measure-common-redis</module>
        <module>measure-common-seata</module>
        <module>measure-common-swagger</module>
        <module>measure-common-security</module>
        <module>measure-common-datascope</module>
        <module>measure-common-datasource</module>
        <module>measure-common-minio</module>
    </modules>

    <artifactId>measure-common</artifactId>
    <packaging>pom</packaging>

    <description>
        measure-common通用模块
    </description>

</project>
